set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'laishulu/emacs-tmux-pane'

set -g @continuum-save-interval 1 # 15 minutes
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind r
bind r source-file ~/.tmux.conf

bind y setw synchronize-panes

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-selection

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

unbind -T copy-mode-vi MouseDragEnd1Pane

# Copy to system clipboard automatically
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

set -g @dracula-plugins 'synchronize-panes continuum network cpu-usage gpu-usage gpu-ram-usage ram-usage battery'

set -g @dracula-battery-label false
set -g @dracula-show-battery-status true

set -g @dracula-cpu-display-load false
set -g @dracula-cpu-usage-label " "

set -g @dracula-force-gpu "NVIDIA"
set -g @dracula-gpu-power-percent true
set -g @dracula-gpu-vram-percent true
set -g @dracula-gpu-power-label "󰢮 "
set -g @dracula-gpu-usage-label "󰢮 "
set -g @dracula-gpu-vram-label "󰢮 "

set -g @dracula-ram-usage-label " "

set -g @dracula-continuum-mode countdown

set -g history-limit 10000

set -g mouse on

set -g default-terminal "screen-256color"

set-option -sa terminal-overrides ".xterm*:Tc"

set -g status-position top 

set-option -sg escape-time 10

set-option -g focus-events on

set-option -a terminal-features 'xterm-256color:RGB'

set -g @dracula-show-powerline true

set -g @dracula-show-edge-icons true

set -g @dracula-show-left-icon "#S"

set -g @dracula-show-flags true

set -g @dracula-synchronize-panes-label "Sync"

set -g @dracula-show-empty-plugins true

foreground='#ffffff'
background='#002451'
highlight='#003f8e'
status_line='#00346e'
comment='#7285b7'
red='#ff9da4'
orange='#ffc58f'
yellow='#ffeead'
green='#d1f1a9'
aqua='#99ffff'
blue='#bbdaff'
purple='#ebbbff'
pane='#4d5057'

set -g "@dracula-cwd-colors" "foreground background"
set -g "@dracula-fossil-colors" "Green background"  
set -g "@dracula-git-colors" "orange background"
set -g "@dracula-hg-colors" "Green background" 
set -g "@dracula-battery-colors" "background foreground"
set -g "@dracula-gpu-usage-colors" "aqua background"
set -g "@dracula-gpu-ram-usage-colors" "aqua background"  
set -g "@dracula-gpu-power-draw-colors" "Green background"
set -g "@dracula-cpu-usage-colors" "blue background"
set -g "@dracula-ram-usage-colors" "background foreground"  
set -g "@dracula-tmux-ram-usage-colors" "Sky background"
set -g "@dracula-network-colors" "Sky background"  
set -g "@dracula-network-bandwidth-colors" "Sky background"
set -g "@dracula-network-ping-colors" "Sky background"
set -g "@dracula-network-vpn-colors" "Sky background"  
set -g "@dracula-attached-clients-colors" "Sky background"
set -g "@dracula-mpc-colors" "Green background"  
set -g "@dracula-spotify-tui-colors" "Green background"
set -g "@dracula-playerctl-colors" "Green background"  
set -g "@dracula-kubernetes-context-colors" "Sky background"
set -g "@dracula-terraform-colors" "Lavender background"
set -g "@dracula-continuum-colors" "red background" 
set -g "@dracula-weather-colors" "orange background"
set -g "@dracula-time-colors" "dark_purple white"  
set -g "@dracula-synchronize-panes-colors" "Sky background"
set -g "@dracula-libre-colors" "Text background"  
set -g "@dracula-ssh-session-colors" "Green background"

run '~/.tmux/plugins/tpm/tpm'
